export const MORPHS = [
  {
    id: "normal",
    nameKo: "노멀",
    nameEn: "Normal / Wild Type",
    category: "base",
    inheritance: "polygenic",
    inheritanceKo: "다지성",
    description:
      "야생형에 가까운 기본 체색입니다. 올리브·벅스킨·브라운 톤이 많고 옆구리 무늬는 적습니다. 다른 모프의 바탕이 됩니다.",
    look: "갈색·올리브 바탕, 무늬가 거의 없거나 약함",
    image: "assets/morphs/normal.jpg",
    aliases: ["노멀", "노말", "와일드", "와일드타입", "일반", "normal", "wild", "wildtype"],
    genes: { lillyWhite: 0, axanthic: 0, phantom: 0, cappuccino: 0 },
    traits: {},
    price: { min: 50000, max: 150000 },
    rarity: 1,
    signature: { white: 0.08, orange: 0.12, yellow: 0.18, dark: 0.28, gray: 0.12, brown: 0.58, spots: 0.04, sat: 0.32 },
  },
  {
    id: "flame",
    nameKo: "플레임",
    nameEn: "Flame",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (선발 교배)",
    description:
      "등(등판)과 머리에만 크림·노란 불꽃 무늬가 있고, 옆구리와 다리에는 무늬가 거의 없습니다. 할리퀸의 약한 형태로 보는 경우가 많습니다.",
    look: "등·머리만 밝은 무늬, 옆구리·다리는 단색",
    image: "assets/morphs/flame.jpg",
    aliases: ["플레임", "flame", "불꽃"],
    genes: {},
    traits: { flame: 1 },
    price: { min: 80000, max: 250000 },
    rarity: 2,
    signature: { white: 0.18, orange: 0.22, yellow: 0.32, dark: 0.3, gray: 0.08, brown: 0.45, spots: 0.05, sat: 0.42 },
  },
  {
    id: "harlequin",
    nameKo: "할리퀸",
    nameEn: "Harlequin",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (선발 교배)",
    description:
      "플레임보다 무늬가 옆구리와 다리까지 내려온 형태입니다. 크레스티드게코에서 가장 흔하고 인기 있는 패턴 모프입니다. 커버리지가 넓을수록 가격이 올라갑니다.",
    look: "크림·노란 무늬가 옆구리와 다리까지 퍼짐",
    image: "assets/morphs/harlequin.jpg",
    aliases: ["할리퀸", "할리", "harley", "harlequin"],
    genes: {},
    traits: { harlequin: 0.8 },
    price: { min: 120000, max: 400000 },
    rarity: 2,
    signature: { white: 0.28, orange: 0.2, yellow: 0.38, dark: 0.22, gray: 0.06, brown: 0.4, spots: 0.06, sat: 0.48 },
  },
  {
    id: "extreme-harlequin",
    nameKo: "익스트림 할리퀸",
    nameEn: "Extreme Harlequin",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (고커버리지)",
    description:
      "할리퀸 무늬가 몸 대부분을 덮은 고퀄리티 개체입니다. 브리더 사이에서는 XXX로 부르기도 하지만, 단일 유전자가 아니라 패턴이 극단적으로 쌓인 표현형입니다.",
    look: "밝은 무늬가 몸 대부분을 덮고 바탕색은 조금만 남음",
    image: "assets/morphs/extreme-harlequin.jpg",
    aliases: ["익스트림할리퀸", "익스트림", "익할", "xxx", "extreme", "extremeharlequin", "슈퍼할리퀸"],
    genes: {},
    traits: { harlequin: 1, extreme: 1 },
    price: { min: 250000, max: 1200000 },
    rarity: 4,
    signature: { white: 0.48, orange: 0.18, yellow: 0.42, dark: 0.12, gray: 0.05, brown: 0.22, spots: 0.05, sat: 0.5 },
  },
  {
    id: "pinstripe",
    nameKo: "핀스트라이프",
    nameEn: "Pinstripe",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 · 우성에 가깝게 유전",
    description:
      "등 양옆으로 융기된 비늘이 크림색 두 줄(핀)을 만듭니다. 줄이 머리부터 꼬리까지 끊기지 않으면 풀 핀, 중간에 끊기면 파셜 핀입니다. 할리퀸·달마시안과 자주 조합됩니다.",
    look: "등을 따라 올라온 크림색 두 줄",
    image: "assets/morphs/pinstripe.jpg",
    aliases: ["핀스트라이프", "핀스", "핀", "pinstripe", "pin", "풀핀"],
    genes: {},
    traits: { pinstripe: 1 },
    price: { min: 180000, max: 700000 },
    rarity: 3,
    signature: { white: 0.22, orange: 0.14, yellow: 0.28, dark: 0.24, gray: 0.08, brown: 0.42, spots: 0.04, sat: 0.4 },
  },
  {
    id: "dalmatian",
    nameKo: "달마시안",
    nameEn: "Dalmatian",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (점 밀도는 선발)",
    description:
      "몸 곳곳에 검은 점(또는 빨간 점)이 찍힙니다. 점의 크기·개수·분포가 퀄리티를 가릅니다. 점이 매우 많으면 슈퍼 달마시안입니다.",
    look: "바탕색 위에 동그란 검은 점",
    image: "assets/morphs/dalmatian.jpg",
    aliases: ["달마시안", "달마", "달마시안점", "dalmatian", "dal", "스팟"],
    genes: {},
    traits: { dalmatian: 0.7 },
    price: { min: 150000, max: 550000 },
    rarity: 3,
    signature: { white: 0.2, orange: 0.12, yellow: 0.35, dark: 0.22, gray: 0.08, brown: 0.28, spots: 0.55, sat: 0.38 },
  },
  {
    id: "super-dalmatian",
    nameKo: "슈퍼 달마시안",
    nameEn: "Super Dalmatian",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (점이 매우 밀집)",
    description:
      "점이 몸 전체를 빽빽하게 덮은 달마시안입니다. 점 크기와 대비가 좋을수록 고가로 거래됩니다.",
    look: "검은 점이 몸 전체에 매우 많음",
    image: "assets/morphs/super-dalmatian.jpg",
    aliases: ["슈퍼달마시안", "슈퍼달마", "superdal", "superdalmatian"],
    genes: {},
    traits: { dalmatian: 1 },
    price: { min: 350000, max: 1300000 },
    rarity: 4,
    signature: { white: 0.16, orange: 0.1, yellow: 0.3, dark: 0.38, gray: 0.1, brown: 0.25, spots: 0.88, sat: 0.36 },
  },
  {
    id: "tiger",
    nameKo: "타이거",
    nameEn: "Tiger",
    category: "pattern",
    inheritance: "polygenic",
    inheritanceKo: "다지성",
    description:
      "옆구리를 가로지르는 호랑이 줄무늬입니다. 줄이 더 꼬이고 깨지면 브린들(Brindle)로 부르기도 합니다.",
    look: "세로·대각선 줄무늬가 옆구리를 감쌈",
    image: "assets/morphs/tiger.jpg",
    aliases: ["타이거", "호랑이", "tiger", "브린들", "brindle"],
    genes: {},
    traits: { tiger: 1 },
    price: { min: 100000, max: 350000 },
    rarity: 2,
    signature: { white: 0.1, orange: 0.28, yellow: 0.2, dark: 0.32, gray: 0.08, brown: 0.4, spots: 0.08, sat: 0.44 },
  },
  {
    id: "halloween",
    nameKo: "할로윈",
    nameEn: "Halloween",
    category: "color",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (검은 바탕 + 오렌지 무늬)",
    description:
      "검정·매우 어두운 바탕에 선명한 오렌지 무늬만 있는 배색입니다. 노랑·크림이 보이면 할로윈으로 보지 않는 것이 일반적입니다.",
    look: "블랙 바탕 + 비비드 오렌지, 노랑/크림 없음",
    image: "assets/morphs/halloween.jpg",
    aliases: ["할로윈", "할윈", "halloween", "할러윈"],
    genes: {},
    traits: { halloween: 1, harlequin: 0.7 },
    price: { min: 200000, max: 800000 },
    rarity: 3,
    signature: { white: 0.04, orange: 0.55, yellow: 0.08, dark: 0.55, gray: 0.1, brown: 0.22, spots: 0.06, sat: 0.62 },
  },
  {
    id: "creamsicle",
    nameKo: "크림시클",
    nameEn: "Creamsicle",
    category: "color",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (오렌지 + 크림)",
    description:
      "오렌지·탠저린 바탕에 화이트·크림 무늬가 올라간 배색입니다. 아이스크림 크림시클처럼 보여 붙은 이름입니다.",
    look: "선명한 오렌지 + 하얀 크림 무늬",
    image: "assets/morphs/creamsicle.jpg",
    aliases: ["크림시클", "creamsicle", "오렌지크림", "탠저린"],
    genes: {},
    traits: { creamsicle: 1, harlequin: 0.6 },
    price: { min: 180000, max: 750000 },
    rarity: 3,
    signature: { white: 0.32, orange: 0.58, yellow: 0.18, dark: 0.1, gray: 0.04, brown: 0.15, spots: 0.04, sat: 0.66 },
  },
  {
    id: "tricolor",
    nameKo: "트라이컬러",
    nameEn: "Tri-color",
    category: "color",
    inheritance: "polygenic",
    inheritanceKo: "다지성 (세 가지 색)",
    description:
      "어두운 바탕 + 오렌지 + 크림/화이트가 한 개체에 분명하게 나뉜 3색 패턴입니다. 색 경계가 선명할수록 가치가 높습니다.",
    look: "어두운 바탕, 오렌지, 크림이 동시에 보임",
    image: "assets/morphs/tricolor.jpg",
    aliases: ["트라이컬러", "트라이", "삼색", "tricolor", "tri-color", "tricolour"],
    genes: {},
    traits: { tricolor: 1, harlequin: 0.7 },
    price: { min: 220000, max: 900000 },
    rarity: 3,
    signature: { white: 0.28, orange: 0.42, yellow: 0.16, dark: 0.32, gray: 0.06, brown: 0.22, spots: 0.05, sat: 0.58 },
  },
  {
    id: "phantom",
    nameKo: "팬텀",
    nameEn: "Phantom",
    category: "genetic",
    inheritance: "recessive",
    inheritanceKo: "열성 (비주얼은 유전자 2개)",
    description:
      "멜라닌이 늘어 전체적으로 어둡고 대비가 깊어집니다. 열성이라 부모 양쪽이 유전자를 가져야 비주얼이 나옵니다. 릴리·핀과 조합하면 팬텀 릴리, 팬텀 핀이 됩니다.",
    look: "전체적으로 매우 어둡고 흰 무늬가 줄어듦",
    image: "assets/morphs/phantom.jpg",
    aliases: ["팬텀", "팬톰", "phantom"],
    genes: { phantom: 2 },
    traits: {},
    price: { min: 200000, max: 800000 },
    rarity: 4,
    signature: { white: 0.06, orange: 0.08, yellow: 0.06, dark: 0.72, gray: 0.22, brown: 0.35, spots: 0.04, sat: 0.22 },
  },
  {
    id: "lilly-white",
    nameKo: "릴리 화이트",
    nameEn: "Lilly White",
    category: "genetic",
    inheritance: "incompleteDominant",
    inheritanceKo: "불완전 우성 · 슈퍼폼은 치사",
    description:
      "2010년대 Lilly Exotics에서 확립된 불완전 우성 유전자입니다. 크림·화이트 커버리지가 넓고 자라면서 더 하얘집니다. 릴리끼리 교배하면 슈퍼 릴리(치사)가 25%라 절대 권장하지 않습니다.",
    look: "몸 옆·배·꼬리가 하얗고 등·머리는 유색",
    image: "assets/morphs/lilly-white.jpg",
    aliases: ["릴리화이트", "릴리", "릴리화", "lilly", "lillywhite", "lily", "lilywhite"],
    genes: { lillyWhite: 1 },
    traits: {},
    price: { min: 250000, max: 2000000 },
    rarity: 5,
    signature: { white: 0.55, orange: 0.28, yellow: 0.16, dark: 0.08, gray: 0.06, brown: 0.12, spots: 0.03, sat: 0.45 },
  },
  {
    id: "axanthic",
    nameKo: "아잔틱",
    nameEn: "Axanthic",
    category: "genetic",
    inheritance: "recessive",
    inheritanceKo: "열성 (노랑·빨강 색소 제거)",
    description:
      "잔토포어(노랑·빨강 색소)가 없어 흑·백·은·회색만 남습니다. 열성이라 비주얼끼리 교배하면 100% 아잔틱, 헷끼리면 25% 비주얼입니다.",
    look: "노랑/오렌지 없이 실버·차콜·화이트",
    image: "assets/morphs/axanthic.jpg",
    aliases: ["아잔틱", "액산틱", "악산틱", "axanthic", "axan"],
    genes: { axanthic: 2 },
    traits: {},
    price: { min: 700000, max: 3500000 },
    rarity: 5,
    signature: { white: 0.22, orange: 0.02, yellow: 0.03, dark: 0.48, gray: 0.62, brown: 0.12, spots: 0.08, sat: 0.12 },
  },
  {
    id: "cappuccino",
    nameKo: "카푸치노",
    nameEn: "Cappuccino",
    category: "genetic",
    inheritance: "incompleteDominant",
    inheritanceKo: "불완전 우성 · 슈퍼폼은 건강 이슈",
    description:
      "한국 Reptile City에서 확인된 불완전 우성입니다. 모카·에스프레소 톤의 어두운 몸과 독특한 두상입니다. 카푸끼리 교배하면 슈퍼 카푸(멜라니스틱)가 나오며 기형 위험이 있어 비추천입니다. 세이블과 같은 좌위입니다.",
    look: "커피색 어두운 몸, 크레스트가 약한 편",
    image: "assets/morphs/cappuccino.jpg",
    aliases: ["카푸치노", "카푸", "cappuccino", "capp", "cap"],
    genes: { cappuccino: 1 },
    traits: {},
    price: { min: 400000, max: 2500000 },
    rarity: 5,
    signature: { white: 0.1, orange: 0.12, yellow: 0.08, dark: 0.58, gray: 0.18, brown: 0.55, spots: 0.04, sat: 0.28 },
  },
  {
    id: "frappuccino",
    nameKo: "프라푸치노",
    nameEn: "Frappuccino",
    category: "combo",
    inheritance: "combo",
    inheritanceKo: "릴리 화이트 + 카푸치노 (각각 불완전 우성)",
    description:
      "릴리 화이트와 카푸치노를 한 개체에 모은 콤보입니다. 커피 바탕에 릴리의 크림 화이트가 올라갑니다. 릴리 × 카푸 교배 시 25% 확률로 나옵니다.",
    look: "모카 바탕 + 넓은 크림 화이트 커버리지",
    image: "assets/morphs/frappuccino.jpg",
    aliases: ["프라푸치노", "프라푸", "frappuccino", "frap", "프라페"],
    genes: { lillyWhite: 1, cappuccino: 1 },
    traits: {},
    price: { min: 800000, max: 4500000 },
    rarity: 5,
    signature: { white: 0.42, orange: 0.12, yellow: 0.1, dark: 0.38, gray: 0.14, brown: 0.4, spots: 0.03, sat: 0.32 },
  },
  {
    id: "lilly-axanthic",
    nameKo: "릴리 아잔틱",
    nameEn: "Lilly Axanthic",
    category: "combo",
    inheritance: "combo",
    inheritanceKo: "릴리 화이트 + 비주얼 아잔틱",
    description:
      "릴잔틱이라고도 합니다. 아잔틱의 흑백 팔레트 위에 릴리의 화이트가 올라간 초고가 콤보입니다. 노랑·오렌지가 전혀 없습니다.",
    look: "실버·차콜 바탕에 순백 무늬, 웜톤 없음",
    image: "assets/morphs/lilly-axanthic.jpg",
    aliases: ["릴리아잔틱", "릴잔틱", "릴리액산틱", "lillyaxanthic", "lilyaxanthic"],
    genes: { lillyWhite: 1, axanthic: 2 },
    traits: {},
    price: { min: 1500000, max: 6000000 },
    rarity: 5,
    signature: { white: 0.48, orange: 0.01, yellow: 0.02, dark: 0.32, gray: 0.55, brown: 0.08, spots: 0.04, sat: 0.1 },
  },
  {
    id: "phantom-lilly",
    nameKo: "팬텀 릴리",
    nameEn: "Phantom Lilly White",
    category: "combo",
    inheritance: "combo",
    inheritanceKo: "릴리 화이트 + 비주얼 팬텀",
    description:
      "팬텀의 멜라닌과 릴리의 화이트가 겹칩니다. 어두운 몸통에 하양 커버리지가 또렷하게 대비됩니다.",
    look: "어두운 몸 + 릴리 화이트 패턴",
    image: "assets/morphs/lilly-white.jpg",
    aliases: ["팬텀릴리", "팬텀릴리화이트", "phantomlilly", "phantomlily"],
    genes: { lillyWhite: 1, phantom: 2 },
    traits: {},
    price: { min: 500000, max: 2200000 },
    rarity: 5,
    signature: { white: 0.4, orange: 0.08, yellow: 0.06, dark: 0.45, gray: 0.18, brown: 0.22, spots: 0.03, sat: 0.28 },
  },
];

export const HET_OPTIONS = [
  { id: "het-axanthic", nameKo: "헷 아잔틱", genes: { axanthic: 1 }, aliases: ["헷아잔틱", "hetaxanthic", "hetax"] },
  { id: "het-phantom", nameKo: "헷 팬텀", genes: { phantom: 1 }, aliases: ["헷팬텀", "hetphantom"] },
];

export function getMorph(id) {
  return MORPHS.find((m) => m.id === id) || null;
}

export function allAliases() {
  const rows = [];
  for (const m of MORPHS) {
    for (const a of m.aliases) {
      rows.push({ alias: normalize(a), morph: m });
    }
  }
  for (const h of HET_OPTIONS) {
    for (const a of h.aliases.concat([h.nameKo.replace(/\s/g, "")])) {
      rows.push({
        alias: normalize(a),
        morph: {
          id: h.id,
          nameKo: h.nameKo,
          nameEn: h.id,
          genes: h.genes,
          traits: {},
          image: "assets/morphs/normal.jpg",
          category: "het",
          price: { min: 80000, max: 400000 },
        },
      });
    }
  }
  rows.sort((a, b) => b.alias.length - a.alias.length);
  return rows;
}

export function normalize(s) {
  return String(s)
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[-_]/g, "")
    .replace(/화이트/g, "화이트");
}

export const GENE_META = {
  lillyWhite: {
    name: "릴리 화이트",
    mode: "incompleteDominant",
    labels: ["없음", "릴리 화이트", "슈퍼 릴리 화이트"],
    lethalSuper: true,
    image: "lilly-white",
  },
  axanthic: {
    name: "아잔틱",
    mode: "recessive",
    labels: ["없음", "헷 아잔틱", "비주얼 아잔틱"],
    image: "axanthic",
  },
  phantom: {
    name: "팬텀",
    mode: "recessive",
    labels: ["없음", "헷 팬텀", "비주얼 팬텀"],
    image: "phantom",
  },
  cappuccino: {
    name: "카푸치노",
    mode: "incompleteDominant",
    labels: ["없음", "카푸치노", "슈퍼 카푸치노"],
    cautionSuper: true,
    image: "cappuccino",
  },
};

export const TRAIT_META = {
  flame: { name: "플레임", image: "flame" },
  harlequin: { name: "할리퀸", image: "harlequin" },
  extreme: { name: "익스트림", image: "extreme-harlequin" },
  pinstripe: { name: "핀스트라이프", image: "pinstripe" },
  dalmatian: { name: "달마시안", image: "dalmatian" },
  tiger: { name: "타이거", image: "tiger" },
  halloween: { name: "할로윈", image: "halloween" },
  creamsicle: { name: "크림시클", image: "creamsicle" },
  tricolor: { name: "트라이컬러", image: "tricolor" },
};
